### ISSUE TITLE
how to compare two sfix numbers?

### ISSUE THREAD

**Issue by maoth** [bristolcrypto/SPDZ-2#54]
I am writing a program which needs to compare two sfix numbers as the condition to get out of a function as below:

if sum_error<eps:
			print_ln('%s',sum_error.reveal())
			print_ln('%s',eps.reveal())
			return coef

the output of two print_ln is:
46.23510932
2.60000035

it shows that the real value of sum_error is still greater than eps, but the program shows it has executed the condition part.
Is that the method of compare these two variants I used is wrong? Why did this happened?
Thanks for your answer.

**Comment by abdelrahamanaly** [comment]
So you want to compare 2 numbers? 
So what I typically would do (there might be already an easy way encoded on SPDZ) is to code an expression such as :
c = sum_error<eps
aux = (sum_error- eps) * c + eps
print_ln("%s", aux.reveal())

don't know if that answers your question

**Comment by maoth** [comment]
Thanks, your method is a good way to get the bigger one or the smaller one between two sfix numbers, it made a great help to me.
But the question is how to get the result of the condition about whether two sfix numbers a<b, it seems that all of the relational operators cannot work in my test.

**Comment by rdragos** [comment]
You need to test the condition at run-time rather than compile time. To do that you need the @if_ construction.

See this example where I test whether 2 MAC values are [equal](https://github.com/bristolcrypto/SPDZ-2/blob/master/Programs/Source/htmac.mpc#L140)

You have other similar constructions such as: @if_else ; see Compiler/oram.py file for usage. They are defined in Compiler/library.py if you are more keen to see the implementations of them.

**Comment by maoth** [comment]
I tried to change if sum_error<eps to
-----------------------------------------
rsum=sum_error.reveal()
reps=eps.reveal()
@if_ (rsum<reps)
def f():
			print_ln('%s',sum_error.reveal())
			print_ln('%s',eps.reveal())
			return coef
------------------------------------------
because the compiler mentioned that Cannot convert '<class 'Compiler.types.sint'>' to integer if I use @if_(sum_error<eps)

but it is contiuning compiling blocks and didn't stop, if I use "if sum_error<eps:" the mpc program can be compiled but give a wrong output, could you tell me how to use @if_ to make it compile successfully? Thanks.

**Comment by rdragos** [comment]
Can you isolate the bug? because I cannot replicate it.
PS: You shouldn't return values inside the if_ blocks.

**Comment by Tikrass** [comment]
Due to the architecture, you always have to keep in mind the the difference between native-Python and run-time commands. All native Python expressions `if`, `else`, `for`, `while`, `return` such as method calls are evaluated by the compiler, such that code is unrolled to possibly duplicate byte-code sequences. For example. the following code produces the same byte-code:

```python
a = cint(0)
for i in range(3):
    a += 1
```
is equivalent to
```python
a = cint(0)
a += 1
a += 1
a += 1
```
Native python instructions behave quite similar to Macros or compiler instructions in other programming languages. e.g. in C/C++.

Because it is not possible to overload the control commands in Python, SPDZ provides his own control instructions in form of annotations or methods. For your example above I suggest to use the following code snippet:

```python
if_then((sum_error<eps).reveal())
print_ln('%s',sum_error.reveal())
print_ln('%s',eps.reveal())
else_then()
    #Do something else?
end_if()
```
The compiler executes and records both segments and separates them into two blocks, because of the method calls in between. Be aware, that the run-time branching commands are actually method calls, hence you can not use indentation to visualize nested if-then-else. 

SPDZ allows you to compare fixed-point numbers `sfix` and `cfix`. However, unless you compare two clear `cint` numbers, the result will be a secret value: `sint` that is either `0` or `1`. Now you have to decide whether this Boolean value leaks private information or not. If it does you cannot use it for branching, because obviously the processor has to know which case to evaluate, hence leak its value. You can work around this issue by computing both branches and using secret multiplication with the Boolean value to select the wanted result eventually. Luckily there are already macros for that:
```python
cond = (sum_error<eps) #compare
a = cint(123) # if case
b = cint(456) # else case
result = cond.if_else(cond, a, b)
print_ln("Result: %s", result.reveal())
```
It should be clear, that evaluating both cases can be quite expensive with regard to the run-time and communication costs. This is why you have to trade off the level of privacy against the performance of your algorithm.
