### ISSUE TITLE
2d array for External IO

### ISSUE THREAD

**Issue by stathisKara** [bristolcrypto/SPDZ-2#56]
Hi, 
I am working on my thesis, which is about SMPC. I've been trying to use your implementation of SPDZ to aggregate some medical data. The concept is multiple parties send arrays of data to the server/computation node and the server returns the result which might be a single value or multiple.
Currently I am working on your Bankers example. However, I really need to use 2d Arrays. 
Some examples having 2 clients:
1) Each client sends an array to the server including the heights of 1000 people. I need to find the max of these 2000 records and send it back to the clients
2) Each client sends an array to the server including the heights of 1000 people. I need to find the average of these 2000 records and send it back to the clients.
3)Each client sends 2 Arrays with 1000 records each and i need to do some computations on those data and send the combined results which could be an array itself.
According to the Bankers example, the client's information would be stored in client_values. I tried using a Array of Arrays, but I realized that it's not implemented. Any suggestions on how to proceed ?

**Comment by MaryLouPap** [comment]
Hello,
I am working on the same project. We would really appreciate an answer of any kind, so that we can somehow proceed.

**Comment by rdragos** [comment]
Hello,

As I see it, the problem you encounter is that the Bankers example every client inputs a set of values (3 it seems from the .cpp file) rather than an array of values.

What you can do is to modify the send_private_inputs() function from the [bankers-bonus-client.cpp](https://github.com/bristolcrypto/SPDZ-2/blob/master/ExternalIO/bankers-bonus-client.cpp) to send M values. Then you have to modify the .mpc program accordingly and instead of having N arrays you can have ONE array with many values (you have to figure out the indexing as well or learn how to use the MultiArray structure - see [types.py](https://github.com/bristolcrypto/SPDZ-2/blob/master/Compiler/types.py)).

AFAIK you can do this simpler in SCALE-MAMBA since there is already some IO functionality implemented.

**Comment by mkskeller** [comment]
There is also a Matrix data structure. The SCALE-MAMBA documentation explains how to use it.
